return {
  { "stevearc/dressing.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  -- { "akinsho/bufferline.nvim", enabled = false },
  { "linux-cultist/venv-selector.nvim", enabled = false },
  { "echasnovski/mini.icons", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "MunifTanjim/nui.nvim", enabled = false },
  { "iamcco/markdown-preview.nvim", enabled = false },
  { "catppuccin/nvim", enabled = false },
  { "neovim/nvim-lspconfig", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
}
